source_list = [
    "Homebrew",  # default / fallback
    "Player's Handbook",
    "Dungeon Master's Guide",
    "Monster Manual",
    "Sword Coast Adventurer's Guide",
    "Xanathar's Guide to Everything",
    "Tasha's Cauldron of Everything",
    "Mordenkainen Presents: Monsters of the Multiverse",
    "Waterdeep: Dragon Heist",
    "Waterdeep: Dungeon of the Mad Mage",
    "Baldur's Gate: Descent into Avernus",
    "Icewind Dale: Rime of the Frostmaiden",
    "Curse of Strahd",
    "Out of the Abyss",
    "Storm King's Thunder",
    "Lost Mine of Phandelver",
    "Tomb of Annihilation",
    "Ghosts of Saltmarsh",
    "Princes of the Apocalypse",
    "Tales from the Yawning Portal",
    "Journeys through the Radiant Citadel",
    "Eberron: Rising from the Last War",
    "Explorer's Guide to Wildemount",
    "Mythic Odysseys of Theros",
    "Strixhaven: Curriculum of Chaos",
    "Spelljammer: Adventures in Space",
    "Planescape: Adventures in the Multiverse",
    "The Wild Beyond the Witchlight",
    "Critical Role: Call of the Netherdeep"
]
